# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\help_program_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HelpProgramInfo(object):
    def setupUi(self, HelpProgramInfo):
        HelpProgramInfo.setObjectName("HelpProgramInfo")
        HelpProgramInfo.resize(400, 313)
        self.centralwidget = QtWidgets.QWidget(HelpProgramInfo)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(".\\../../../Pictures/jpg.jpg"))
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        HelpProgramInfo.setCentralWidget(self.centralwidget)

        self.retranslateUi(HelpProgramInfo)
        QtCore.QMetaObject.connectSlotsByName(HelpProgramInfo)

        # ->> Click to exit
        self.centralwidget.mouseReleaseEvent = lambda e: QtCore.QCoreApplication.instance().quit()

    def retranslateUi(self, HelpProgramInfo):
        _translate = QtCore.QCoreApplication.translate
        HelpProgramInfo.setWindowTitle(_translate("HelpProgramInfo", "프로그램 정보"))
        self.label_2.setText(_translate("HelpProgramInfo", "개발: 이은학"))
        self.label_3.setText(_translate("HelpProgramInfo", "파일 관리자"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HelpProgramInfo = QtWidgets.QMainWindow()
    ui = Ui_HelpProgramInfo()
    ui.setupUi(HelpProgramInfo)
    HelpProgramInfo.show()
    sys.exit(app.exec_())
